dist: trusty
language: java
jdk:
  - oraclejdk8

install: true
script:
  - gradle clean build

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/

deploy:
  provider: bintray
  skip_cleanup: true
  file: "bintray.json"
  user: maslick
  key: $BINTRAY_API_KEY
