language: java
dist: trusty
jdk:
  - oraclejdk8

install: true
script:
  - ./gradlew clean build

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: bintray
  skip_cleanup: true
  file: target/klassy-1.0.SNAPSHOT.jar
  user: maslick
  key: $BINTRAY_API_KEY